# Forgejo web auth failure filter.
# Matches lines like:
#   2026/05/13 22:06:16 ...auth.go:221:SignInPost() [W] Failed authentication attempt for fake from 89.88.192.29:0: user does not exist ...

[Definition]
failregex = ^.*\[W\] Failed authentication attempt for .* from <HOST>:\d+:.*$

ignoreregex =
